app_id: "fe2ca352-fdb7-4ba0-ae5f-d0da2ecd7223"
app_secret: ".j121i1T_R4.~aoUDf3O0o2C-AYp9~GU5R"
redirect: "https://ahl-teams.herokuapp.com/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/common"